### ISSUE TITLE
Update for new versions of Signal

### ISSUE THREAD

**Issue by gartnera** [grandchild/Signal-Desktop-Darkskin#1]
As you might have noticed, there Signal'ss css has had [quite a few updates recently](https://github.com/WhisperSystems/Signal-Desktop/commits/master/stylesheets/manifest.css). Do you have any plans to update the dark skin patch?

**Comment by grandchild** [comment]
Yes I have. But I'm in South America right now, and am stepping through the jungle and stuff. I'll be back in a few days and then I'll tweak it for the updates... :)

**Comment by aksratamo** [comment]
still waiting for the update. but great work man! Im wondering so much why is darkskin not already in signal desktop

**Comment by grandchild** [comment]
Got back on Friday. Worked on it a little today... It's coming. Patience, young Mr Riddle.

**Comment by grandchild** [comment]
There you go folks... Have fun.

Closed with e462735.

**Comment by claenn** [comment]
thks for this nice blackedout

2016-04-13 2:32 GMT+02:00 jakob notifications@github.com:
