### ISSUE TITLE
0.10.0 release

### ISSUE THREAD

**Issue by smichel17** [grandchild/Signal-Desktop-Darkskin#2]
> If there is an update to Signal Desktop and there happens to be no related release yet, _please do open an issue about it, if there isn't one yet_ and I will get to it.

As requested :)

**Comment by grandchild** [comment]
Super, thanks, I will probably do it on Monday!

**Comment by grandchild** [comment]
Super, thanks, I will probably do it on Monday!

**Comment by grandchild** [comment]
A cursory glance at the commits since 0.9.0 shows that there are probably no changes to the CSS. So the 0.9.0 version should still work just fine until I update later...

**Comment by grandchild** [comment]
Closed by 1cccf622fef8c41b4424e8f1208c73515f742b24
